name: Build ULS APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java and Android
      uses: android-actions/setup-android@v3
      
    - name: Build APK
      run: |
        git clone https://github.com/Simple-Mobile-WebView/SimpleWebView.git
        cd SimpleWebView
        sed -i 's|http://www.example.com|https://testase.gt.tc/uls/|g' app/src/main/java/com/simple/mobile/webview/MainActivity.java
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: uls-app
        path: SimpleWebView/app/build/outputs/apk/debug/app-debug.apk
