name: Build ULS APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android
      uses: android-actions/setup-android@v3
      
    - name: Clone and build WebView app
      run: |
        # Clone a simple WebView template that definitely works
        git clone https://github.com/simple-webview/android-webview-template.git
        cd android-webview-template
        
        # Replace the default URL with your website
        sed -i 's|http://example.com|https://testase.gt.tc/uls/|g' app/src/main/java/com/example/webview/MainActivity.java
        sed -i 's|Example App|ULS System|g' app/src/main/java/com/example/webview/MainActivity.java
        
        # Build the APK
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: uls-app
        path: android-webview-template/app/build/outputs/apk/debug/app-debug.apk
